version: "3.9"

services:
  postgres:
    image: postgis/postgis:14-3.4
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_USER=$DATABASE_ROLE
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - $DATABASE_PORT:5432

volumes:
  postgres:
