# Generated by Django 4.2.2 on 2024-03-10 23:47

from django.db import migrations

DATA = [
    {
        'name': 'Soil Sample',
    },
    {
        'name': 'Fertilization Area',
    },
]


def insert_activity_types(apps, schema_editor):
    ActivityType = apps.get_model('activities', 'ActivityType')
    for activity_type in DATA:
        if not ActivityType.objects.filter(name=activity_type['name']).exists():
            ActivityType.objects.create(**activity_type)


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_activity_types, reverse_code=migrations.RunPython.noop),
    ]
