# Generated by Django 4.2.2 on 2024-03-11 00:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_fixture_activity_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='location',
        ),
        migrations.AddField(
            model_name='soilsample',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Location of the soil sample', null=True, srid=4326),
        ),
    ]
