# Generated by Django 4.2.2 on 2024-03-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activity_location_soilsample_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the activity', max_length=255),
        ),
    ]
