# Generated by Django 4.2.2 on 2024-03-11 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizationarea',
            name='activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilization_area', to='activities.activity'),
        ),
        migrations.AlterField(
            model_name='soilsample',
            name='activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soil_sample', to='activities.activity'),
        ),
    ]
