# Generated by Django 4.2.2 on 2024-03-11 01:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_fertilizationarea_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilsample',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Location of the soil sample', null=True, srid=4326),
        ),
    ]
